### ISSUE TITLE
failed to start but running

### ISSUE THREAD

**Issue by ghost** [pimoroni/clean-shutdown#11]
I am using lipo shim.
I did used pimoroni dashboard on last rasbian OS to install this soft.

I am getting error message in journal
![e2](https://user-images.githubusercontent.com/9103155/33996578-ebeed5bc-e0e1-11e7-993c-82f6d09ce12a.png)

so I did check running processes 

![e1](https://user-images.githubusercontent.com/9103155/33996561-e191bd14-e0e1-11e7-9568-224afb3e8355.png)

strange, it is running, and when my batter get low it is switch off my raspberry.

I did check systemd service and there is also mentioned error message
![e3](https://user-images.githubusercontent.com/9103155/33996684-334d4434-e0e2-11e7-9259-c9523e3b7caa.png)

I am not sure why there are two services with very similar name. I think it is mistake
cleanshud.service and cleanshutd.service
see last screenshot with red underline

**Comment by Gadgetoid** [comment]
Sorry for the radio silence, did you ever get anywhere with this?

I'm currently working on a Python replacement for cleanshutd that works in new features and switches to low-level polling so that it's more responsive. One of the things I'll be doing is switching to pure systemd (the current setup uses a typical sprawling init script) which should help make issues like this easier to hunt down, or eliminate them altogether!

**Comment by ghost** [comment]
well, I did reinstall rasbian on my card and it is working now.
it is good to hear that you will switch to pure systemd ...
